version: '3'

services: 

  laravel:
    image: justronis/laravel-op
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    image: justronis/nginx-reverse
    container_name: nginx
    networks:
      - laranet
    ports: 
      - "8080:80"

networks:
  laranet:
    driver: bridge
  