version: '3.1'

services:
  app:
    build:
      context: ../../nodejs
    container_name: node-app
    networks:
      - node-network
    volumes:
      - ../../nodejs:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
     - db
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes:
      - ../../mysql:/var/lib/mysql
    environment:
       - MYSQL_DATABASE=nodedb
       - MYSQL_ROOT_PASSWORD=admin
    networks: 
      - node-network


networks:
  node-network:
    driver: bridge

