# Quero uma imagem da última versão do nginx, porém preciso que ela já venha com o vim instalado para que eu não precise futuramente acessar o container manualmente e instalar o vim para poder utiliza-lo

FROM nginx:latest

RUN apt-get update
RUN apt-get install vim -y

