#Com o WORKDIR defimos o diretório onde iremos trabalhar dentro do container.

#Ou seja, no caso abaixo estamos pedindo para criar uma pasta dentro do container e estamos definindo que o ponto de entrada será essa pasta



from nginx:latest

WORKDIR /app

