version: '3'

services:
  laravel:
    build:
      context: ../../laravel-optimized
      dockerfile: Dockerfile.prod
    image: justronis/laravel-op
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    build:
      context: ../../nginx-reverseProxy-php
      dockerfile: Dockerfile.prod
    image: justronis/nginx-reverse
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
